title: Tianyu Liu
description: Homepage
author: Tianyu Liu (刘天宇)
logo: /static/img/photo.jpg
github: https://github.com/tyliupku
about: CS Ph.D. @ PKU

baseurl: ""
url: ""

allowsearch: false

disqus_shortname: Tianyu Liu
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: false
tagarray: [ahha,ajiaj]

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
